Lesson 4: Add appeal form (web & api)
Skurik-SA/fefu_backend_3_6 pull request #4
Opened 2022-05-30 08:19 UTC by Skurik-SA

2022-06-01 13:49 UTC, chrn-feip commented
@Skurik-SA сделайте ребейз ветки, чтобы остались коммиты только по ДЗ 4. И конфликты пофиксите.

2022-06-11 07:10 UTC, chrn-feip requested changes

2022-06-11 07:10 UTC, chrn-feip commented on fefu-app2/app/Http/Controllers/Web/AppealWebController.php
> +        $appeal->phone = PhoneSanitizer::sanitize($data['phone']??null);
Здесь нет необходиомсти писать ?? null, т.к. в веб-контроллере все поля будут в запросе, потому что они все есть в форме на странице. В апи мы это пишем, потому что запросто можем телефон и/или почту не указывать в параметрах запроса.

2022-06-11 07:10 UTC, chrn-feip commented on fefu-app2/app/Http/Requests/StoreAppealRequest.php
> +class StoreAppealRequest extends FormRequest
Это не нужно

2022-06-11 07:10 UTC, chrn-feip commented on fefu-app2/app/Http/Requests/UpdateAppealRequest.php
> +class UpdateAppealRequest extends FormRequest
Это не нужно

2022-06-11 07:10 UTC, chrn-feip commented on fefu-app2/app/Policies/AppealPolicy.php
> +class AppealPolicy
У нас нет никаких ограничений по тому, кто может оставлять обратную связь. Соответственно, и нет  необходимости вводить класс политики, который всем всё разрешает.

2022-06-11 07:10 UTC, chrn-feip commented on fefu-app2/database/factories/AppealFactory.php
> +class AppealFactory extends Factory
Не нужно

2022-06-11 07:10 UTC, chrn-feip commented on fefu-app2/database/seeders/AppealSeeder.php
> +class AppealSeeder extends Seeder
Не нужно

2022-06-16 07:53 UTC, chrn-feip commented on fefu-app2/app/Http/Controllers/Web/AppealWebController.php
> +        $appeal->phone = PhoneSanitizer::sanitize($data['phone']??null);
Почты строкой ниже это тоже касается

2022-06-16 07:54 UTC, chrn-feip commented on fefu-app2/app/Http/Controllers/Web/AppealWebController.php
> +        $appeal->phone = PhoneSanitizer::sanitize($data['phone']??null);
@Skurik-SA

2022-06-16 07:56 UTC, Skurik-SA commented on fefu-app2/app/Http/Controllers/Web/AppealWebController.php
> +        $appeal->phone = PhoneSanitizer::sanitize($data['phone']??null);
Убрал

2022-06-16 08:38 UTC, merged